# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
   - name: WhitespaceTokenizer   # splits input text into tokens based on whitespace characters 
   - name: LexicalSyntacticFeaturizer   # uses the spaCy library to parse the user input and extract various features
   - name: CountVectorsFeaturizer   # takes text inputs and creates a bag-of-words representation of each input.
   
     OOV_token: oov
     token_pattern: (?u)\b\w+\b
   - name: CountVectorsFeaturizer  
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: DIETClassifier  #it does both intent classification and entity extraction
     epochs: 50
     ranking_length: 5
     constrain_similarities: true
   - name: EntitySynonymMapper   # used to handle cases where users may refer to the same entity using different names or phrases
   - name: FallbackClassifier    # used to handle out-of-scope or unrecognizable user input in a conversational AI application
     threshold: 0.3
     ambiguity_threshold: 0.1
   - name: SpacyNLP  # Perform advanced NLP tasks using spaCy
     model: "en_core_web_md"
   - name: LanguageModelFeaturizer  
     model_name: gpt


policies:
   - name: MemoizationPolicy  # used to predict the next action in a conversation by remembering the previous conversation turns and the action that was taken in response to them. 
     max_history: 5
   - name: RulePolicy  # used to define rules
     core_fallback_threshold: 0.3
     core_fallback_action_name: action_default_fallback
     enable_fallback_prediction: true
     restrict_rules: true
     check_for_contradictions: true
   - name: TEDPolicy   # uses the Transformer architecture to encode the conversation history and generate the next response. 
     #max_history: 5   # default is none, so it takes into account the whole dialogue
     epochs: 50
     constrain_similarities: true
     #split_similarities_by_comma: true or false 
   - name: UnexpecTEDIntentPolicy
     epochs: 50
     tolerance: 0.1
   #- name: FormPolicy     # Manage and validate form-based conversations
     #max_history: 5
   #  validation_set_ratio: 0.1  # Portion of data used for validation during training
   #  augmentation_factor: 20  # Augmentation factor for data augmentation
   #  core_fallback_threshold: 0.2  # Threshold for the core fallback action
   #- name: MappingPolicy  # Map user inputs to intents or actions using predefined rules
   #  denied_classification_penalty: -0.5  # Penalty for denied classification
   #  influence_conversation: false  # Whether to influence the conversation
   #- name: ResponseSelector  # Select personalized responses based on user queries
   #  retrieval_intent: "retrieve_response"  # The intent used for response retrieval
   #  deny_suggestion_intent: "deny"  # The intent to deny response suggestions
   #  model_confidence: "low"  # Confidence level for selecting a response
   #  project_path: "./projects"  # Path to the response selection model project directory
   #  stop_words: "data/stopwords.txt"  # Path to stop words list for response selection
   #- name: ReinforcementLearningPolicy  # Fine-tune responses based on user feedback
     #max_history: 5
   #  epochs: 50  
   #  model_confidence: "low"  # Confidence level for model predictions
   #  random_seed: 42  # Set a random seed for reproducibility

